# Generated by Django 4.2.5 on 2023-09-13 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='descriptions',
            new_name='descripton',
        ),
    ]
